name: Build and Test

on:
  push:
    branches:
    - V13
  pull_request:
    branches:
    - V13

permissions:
  contents: read
  packages: read

jobs:

  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          nuget restore

      - name: define env variables
        run: |
          echo "APP_VERSION=12.3.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: |
          dotnet build QualificationRunner.sln /p:Version=${{env.APP_VERSION}}

      - name: Install PK-Sim Portable (for Integration Tests)
        uses: ./.github/actions/install-pksim-portable
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pksim-workflow: build-nightly_v13.yml
          pksim-branch: V13

      - name: Test
        run: dotnet test QualificationRunner.sln --no-build -v normal  --logger:"html;LogFileName=../../../testLog_Windows.html"

      - name: Push test log as artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: testLog_Windows
          path: ./**/testLog*.html
